package com.example.future_sur_taux.domain.enumeration;
public enum BondNature {
  CERTIFICATE_OF_DEPOSIT,
  ISSUED_BOND_DEBT,
  DEBT_SECURITIES_ISSUED,
  SUBORDINATED_TERM_SECURITIES,
  SUBORDINATED_FIXED_TERM_SECURITIES_ISSUED_TO_CREDIT_INSTITUTIONS_AND_SIMILAR_ENTITIES,
  PERPERTUAL_SUBORDINATED_SECURITIES,
  PERPERTUAL_SUBORDINATED_SECURITIES_ISSUED_TO_CREDIT_INSTITUTIONS_AND_SIMILAR_ENTITIES,
  CERTIFICATES_OF_DEPOSIT,
  BONS_SOCIETES_FINANCEMENT,
  BILLETS_TRESORERIE,
  FIXED_RATE_TREASURY_BILLS_WITH_PRE_COUNTED_INTEREST,
  FIXED_RATE_ANNUAL_INTEREST_TREASURY_BILLS,
  MEDIUM__AND_LONG_TERM_TREASURY_BONDS_MATURING_IN_2_TO_50_YEARS,
  ASSIMILABLE_TREASURY_BILLS_LESS_THAN_ONE_YEAR,
}
